=== Power535/ilixi/bin/osk/keyboard.dtd
<!ELEMENT keyboard (row)>

<!ELEMENT row (key+)>
	<!ATTLIST row id ID #REQUIRED height CDATA #IMPLIED gap CDATA #IMPLIED>

<!ELEMENT key (symbol*, icon?)>
	<!ATTLIST key id ID #REQUIRED>
	<!ELEMENT icon (#PCDATA)>

<!ELEMENT symbol (#PCDATA)>
	<!ATTLIST symbol states CDATA #REQUIRED>

=== Power535/ilixi/apps/osk/osk-alpha.xml
<?xml version="1.0"?>
<!DOCTYPE keyboard PUBLIC "-//ilixi//DTD keyboard v1//EN" "http://www.ilixi.org/dtd/keyboard.dtd">

<keyboard>
	<row id="rowQ" height="%25">
		<key id="q">
			<symbol states="1">q</symbol>
			<symbol states="2">Q</symbol>
		</key>

		<key id="w">
			<symbol states="1">w</symbol>
			<symbol states="2">W</symbol>
		</key>

		<key id="e">
			<symbol states="1">e</symbol>
			<symbol states="2">E</symbol>
		</key>

		<key id="r">
			<symbol states="1">r</symbol>
			<symbol states="2">R</symbol>
		</key>

		<key id="t">
			<symbol states="1">t</symbol>
			<symbol states="2">T</symbol>
		</key>

		<key id="y">
			<symbol states="1">y</symbol>
			<symbol states="2">Y</symbol>
		</key>

		<key id="u">
			<symbol states="1">u</symbol>
			<symbol states="2">U</symbol>
		</key>

		<key id="i">
			<symbol states="1">i</symbol>
			<symbol states="2">I</symbol>
		</key>

		<key id="o">
			<symbol states="1">o</symbol>
			<symbol states="2">O</symbol>
		</key>

		<key id="p">
			<symbol states="1">p</symbol>
			<symbol states="2">P</symbol>
		</key>

	</row>

	<row id="rowA" gap="10" height="%25">

		<key id="a">
			<symbol states="1">a</symbol>
			<symbol states="2">A</symbol>
		</key>

		<key id="s">
			<symbol states="1">s</symbol>
			<symbol states="2">S</symbol>
		</key>

		<key id="d">
			<symbol states="1">d</symbol>
			<symbol states="2">D</symbol>
		</key>

		<key id="f">
			<symbol states="1">f</symbol>
			<symbol states="2">F</symbol>
		</key>

		<key id="g">
			<symbol states="1">g</symbol>
			<symbol states="2">G</symbol>
		</key>

		<key id="h">
			<symbol states="1">h</symbol>
			<symbol states="2">H</symbol>
		</key>

		<key id="j">
			<symbol states="1">j</symbol>
			<symbol states="2">J</symbol>
		</key>

		<key id="k">
			<symbol states="1">k</symbol>
			<symbol states="2">K</symbol>
		</key>

		<key id="l">
			<symbol states="1">l</symbol>
			<symbol states="2">L</symbol>
		</key>

	</row>

	<row id="rowShift" height="%25">

		<key id="Shift" modifier="yes">
			<icon>@DATADIR:osk/caps.png</icon>
			<rollStates>1, 2</rollStates>
		</key>

		<key id="z">
			<symbol states="1">z</symbol>
			<symbol states="2">Z</symbol>
		</key>

		<key id="x">
			<symbol states="1">x</symbol>
			<symbol states="2">X</symbol>
		</key>

		<key id="c">
			<symbol states="1">c</symbol>
			<symbol states="2">C</symbol>
		</key>

		<key id="v">
			<symbol states="1">v</symbol>
			<symbol states="2">V</symbol>
		</key>

		<key id="b">
			<symbol states="1">b</symbol>
			<symbol states="2">B</symbol>
		</key>

		<key id="n">
			<symbol states="1">n</symbol>
			<symbol states="2">N</symbol>
		</key>

		<key id="m">
			<symbol states="1">m</symbol>
			<symbol states="2">M</symbol>
		</key>

		<key id="BackSpace" repeatable="yes" special="yes">
			<symbol states="1, 2" unicode="yes">BACKSPACE</symbol>
			<icon>@DATADIR:osk/backspace.png</icon>
		</key>

	</row>

	<row id="Bottom" height="%25">
		<key id="Helper" helper="yes">
			<symbol states="1, 2">JP</symbol>
		</key>

		<key id="ABC" sticky="yes">
			<symbol states="1">abc</symbol>
			<symbol states="2">ABC</symbol>
		</key>

		<key id="Left" special="yes">
			<symbol states="1, 2">CURSOR_LEFT</symbol>
			<icon>@DATADIR:osk/left_arrow.png</icon>
		</key>

		<key id="Space" constraint="extend" repeatable="yes">
			<symbol states="1, 2">
			</symbol>
			<icon>@DATADIR:osk/space.png</icon>
		</key>

		<key id="Right" special="yes">
			<symbol states="1, 2">CURSOR_RIGHT</symbol>
			<icon>@DATADIR:osk/right_arrow.png</icon>
		</key>

		<key id="Return" special="yes">
			<symbol states="1, 2">RETURN</symbol>
			<icon>@DATADIR:osk/return.png</icon>
		</key>
	</row>

</keyboard>

=== Power535/ilixi/apps/osk/osk-numpad.xml
<?xml version="1.0"?>
<!--
<!DOCTYPE app SYSTEM "http://www.ilixi.org/keyboard.dtd">
-->
<!DOCTYPE keyboard SYSTEM "keyboard.dtd">

<keyboard>
    <row id="n123" height="%25">
        <key id="N1" repeatable="yes" special="yes" cycle="yes">
            <symbol states="1, 2" unicode="yes">1BACKSPACE</symbol>
            <icon>@DATADIR:calc/backspace.png</icon>
        </key>

        <key id="N2" cycle="yes">
            <symbol states="1">2abc</symbol>
            <symbol states="2">2ABC</symbol>
        </key>

        <key id="N3" cycle="yes">
            <symbol states="1">3def</symbol>
            <symbol states="2">3DEF</symbol>
        </key>
    </row>

    <row id="n456" height="%25">
        <key id="N4" cycle="yes">
            <symbol states="1">4ghi</symbol>
            <symbol states="2">4GHI</symbol>
        </key>

        <key id="N5" cycle="yes">
            <symbol states="1">5jkl</symbol>
            <symbol states="2">5JKL</symbol>
        </key>

        <key id="N6" cycle="yes">
            <symbol states="1">6mno</symbol>
            <symbol states="2">6MNO</symbol>
        </key>
    </row>

    <row id="n789" height="%25">
        <key id="N7" cycle="yes">
            <symbol states="1">7pqrs</symbol>
            <symbol states="2">7PQRS</symbol>
        </key>

        <key id="N8" cycle="yes">
            <symbol states="1">8tuv</symbol>
            <symbol states="2">8TUV</symbol>
        </key>

        <key id="N9" cycle="yes">
            <symbol states="1">9wxyz</symbol>
            <symbol states="2">9WXYZ</symbol>
        </key>
    </row>

    <row id="n0" height="%25">
        <key id="Nstar" cycle="yes">
            <symbol states="1">*+-:;</symbol>
            <symbol states="2">*+-:;</symbol>
        </key>

        <key id="N0" cycle="yes">
            <symbol states="1">0 ,.</symbol>
            <symbol states="2">0 ,.</symbol>
        </key>

        <key id="Nhash" modifier="yes" cycle="yes">
            <symbol states="1, 2" unicode="yes">#</symbol>
            <icon>@DATADIR:osk/caps.png</icon>
            <rollStates>1, 2</rollStates>
        </key>
    </row>


</keyboard>

=== Power535/ilixi/apps/osk/osk-numeric.xml
<?xml version="1.0"?>
<!DOCTYPE keyboard PUBLIC "-//ilixi//DTD keyboard v1//EN" "http://www.ilixi.org/dtd/keyboard.dtd">

<keyboard>
	<row id="row1" height="%20">
		<key id="N1">
			<symbol states="1">1</symbol>
		</key>

		<key id="N2">
			<symbol states="1">2</symbol>
		</key>

		<key id="N3">
			<symbol states="1">3</symbol>
		</key>

	</row>

	<row id="row2" height="%20">
		<key id="N4">
			<symbol states="1">4</symbol>
		</key>

		<key id="N5">
			<symbol states="1">5</symbol>
		</key>

		<key id="N6">
			<symbol states="1">6</symbol>
		</key>
	</row>

	<row id="row3" height="%20">
		<key id="N7">
			<symbol states="1">7</symbol>
		</key>

		<key id="N8">
			<symbol states="1">8</symbol>
		</key>

		<key id="N9">
			<symbol states="1">9</symbol>
		</key>
	</row>

	<row id="row4" height="%20">
		<key id="Dot">
			<symbol states="1">.</symbol>
		</key>

		<key id="N0">
			<symbol states="1">0</symbol>
		</key>

		<key id="BackSpace" repeatable="yes" special="yes">
			<symbol states="1" unicode="yes">BACKSPACE</symbol>
			<icon>@DATADIR:osk/backspace.png</icon>
		</key>

	</row>

	<row id="row5" height="%20">
		<key id="Left" special="yes">
			<symbol states="1">CURSOR_LEFT</symbol>
			<icon>@DATADIR:osk/left_arrow.png</icon>
		</key>


		<key id="Right" special="yes">
			<symbol states="1">CURSOR_RIGHT</symbol>
			<icon>@DATADIR:osk/right_arrow.png</icon>
		</key>

		<key id="Return" special="yes">
			<symbol states="1">RETURN</symbol>
			<icon>@DATADIR:osk/return.png</icon>
		</key>

	</row>

</keyboard>

=== Power535/ilixi/bin/osk/keyboard.xml
<?xml version="1.0"?>
<!--
<!DOCTYPE app SYSTEM "http://www.ilixi.org/keyboard.dtd">
-->
<!DOCTYPE keyboard SYSTEM "keyboard.dtd">

<keyboard>    
    <row id="numbers" height="%15">
        <key id="N1">
            <symbol states="0, 1, 2">1</symbol>
            <symbol states="3">¶</symbol>
            <symbol states="4">≡</symbol>
        </key>
        
        <key id="N2">
            <symbol states="0, 1, 2">2</symbol>
            <symbol states="3">~</symbol>
            <symbol states="4">≤</symbol>
        </key>
        
        <key id="N3">
            <symbol states="0, 1, 2">3</symbol>
            <symbol states="3">=</symbol>
            <symbol states="4">❤</symbol>
        </key>
        
        <key id="N4">
            <symbol states="0, 1, 2">4</symbol>
            <symbol states="3">_</symbol>
            <symbol states="4">♡</symbol>
        </key>
                
        <key id="N5">
            <symbol states="0, 1, 2">5</symbol>
            <symbol states="3">&lt;</symbol>
            <symbol states="4">✩</symbol>
        </key>
        
        <key id="N6">
            <symbol states="0, 1, 2">6</symbol>
            <symbol states="3">></symbol>
            <symbol states="4">✪</symbol>
        </key>
        
        <key id="N7">
            <symbol states="0, 1, 2">7</symbol>
            <symbol states="3">{</symbol>
            <symbol states="4">●</symbol>
        </key>
        
        <key id="N8">
            <symbol states="0, 1, 2">8</symbol>
            <symbol states="3">}</symbol>
            <symbol states="4">○</symbol>
        </key>
        
        <key id="N9">
            <symbol states="0, 1, 2">9</symbol>
            <symbol states="3">[</symbol>
            <symbol states="4">;o)</symbol>
        </key>
        
        <key id="N0">
            <symbol states="0, 1, 2">0</symbol>
            <symbol states="3">]</symbol>
            <symbol states="4">:(</symbol>
        </key>
    </row>
            
        
        
    <row id="rowQ" height="%20">
        <key id="q">
            <symbol states="1">q</symbol>
            <symbol states="2">Q</symbol>
            <symbol states="3">@</symbol>
            <symbol states="4">|</symbol>
            <symbol states="5">:-[</symbol>
        </key>
		
		<key id="w">
            <symbol states="1">w</symbol>
            <symbol states="2">W</symbol>
            <symbol states="3">#</symbol>
            <symbol states="4">$</symbol>
            <symbol states="5">lol</symbol>
        </key>
        
        <key id="e">
            <symbol states="1">e</symbol>
            <symbol states="2">E</symbol>
            <symbol states="3">%</symbol>
            <symbol states="4">€</symbol>
            <symbol states="5">:-)</symbol>
        </key>

        <key id="r">
            <symbol states="1">r</symbol>
            <symbol states="2">R</symbol>
            <symbol states="3">&amp;</symbol>
            <symbol states="4">£</symbol>
            <symbol states="5">:-(</symbol>
        </key>
        
        <key id="t">
            <symbol states="1">t</symbol>
            <symbol states="2">T</symbol>
            <symbol states="3">*</symbol>
            <symbol states="4">¥</symbol>
            <symbol states="5">;-)</symbol>
        </key>
        
        <key id="y">
            <symbol states="1">y</symbol>
            <symbol states="2">Y</symbol>
            <symbol states="3">/</symbol>
            <symbol states="4">¢</symbol>
            <symbol states="5">:-P</symbol>
        </key>
        
        <key id="u">
            <symbol states="1">u</symbol>
            <symbol states="2">U</symbol>
            <symbol states="3">-</symbol>
            <symbol states="4">₩</symbol>
            <symbol states="5">=-o</symbol>
        </key>
        
        <key id="i">
            <symbol states="1">i</symbol>
            <symbol states="2">I</symbol>
            <symbol states="3">+</symbol>
            <symbol states="4">§</symbol>
            <symbol states="5">:-*</symbol>
        </key>
        
        <key id="o">
            <symbol states="1">o</symbol>
            <symbol states="2">O</symbol>
            <symbol states="3">(</symbol>
            <symbol states="4">^</symbol>
            <symbol states="5">:o</symbol>
        </key>
        
        <key id="p">
            <symbol states="1">p</symbol>
            <symbol states="2">P</symbol>
            <symbol states="3">)</symbol>
            <symbol states="4">`</symbol>
            <symbol states="5">B-)</symbol>
        </key>
        
    </row>
    
    
    
    <row id="rowA" gap="10" height="%20">
        
        <key id="a">
            <symbol states="1">a</symbol>
            <symbol states="2">A</symbol>
            <symbol states="3">¤</symbol>
            <symbol states="4">|</symbol>
            <symbol states="5">:-[</symbol>
        </key>
		
		<key id="s">
            <symbol states="1">s</symbol>
            <symbol states="2">S</symbol>
            <symbol states="3">?</symbol>
            <symbol states="4">$</symbol>
            <symbol states="5">lol</symbol>
        </key>
        
        <key id="d">
            <symbol states="1">d</symbol>
            <symbol states="2">D</symbol>
            <symbol states="3">!</symbol>
            <symbol states="4">€</symbol>
            <symbol states="5">:-)</symbol>
        </key>

        <key id="f">
            <symbol states="1">f</symbol>
            <symbol states="2">F</symbol>
            <symbol states="3">"</symbol>
            <symbol states="4">£</symbol>
            <symbol states="5">:-(</symbol>
        </key>
        
        <key id="g">
            <symbol states="1">g</symbol>
            <symbol states="2">G</symbol>
            <symbol states="3">'</symbol>
            <symbol states="4">¥</symbol>
            <symbol states="5">;-)</symbol>
        </key>
        
        <key id="h">
            <symbol states="1">h</symbol>
            <symbol states="2">H</symbol>
            <symbol states="3">:</symbol>
            <symbol states="4">¢</symbol>
            <symbol states="5">:-P</symbol>
        </key>
        
        <key id="j">
            <symbol states="1">j</symbol>
            <symbol states="2">J</symbol>
            <symbol states="3">;</symbol>
            <symbol states="4">₩</symbol>
            <symbol states="5">=-o</symbol>
        </key>
        
        <key id="k">
            <symbol states="1">k</symbol>
            <symbol states="2">K</symbol>
            <symbol states="3">,</symbol>
            <symbol states="4">§</symbol>
            <symbol states="5">:-*</symbol>
        </key>
        
        <key id="l">
            <symbol states="1">l</symbol>
            <symbol states="2">L</symbol>
            <symbol states="3">(</symbol>
            <symbol states="4"></symbol>
            <symbol states="5">:o</symbol>
        </key>
 
    </row>

	<row id="rowShift" height="%20">
	            
        <key id="Shift" modifier="yes" states="0, 1" constraint="extend">
            <icon>@DATADIR:shift.png</icon>
        </key>
        
        <key id="z">
            <symbol states="1">z</symbol>
            <symbol states="2">Z</symbol>
            <symbol states="3">¤</symbol>
            <symbol states="4">|</symbol>
            <symbol states="5">:-[</symbol>
        </key>
		
		<key id="x">
            <symbol states="1">x</symbol>
            <symbol states="2">X</symbol>
            <symbol states="3">?</symbol>
            <symbol states="4">$</symbol>
            <symbol states="5">lol</symbol>
        </key>
        
        <key id="c">
            <symbol states="1">c</symbol>
            <symbol states="2">C</symbol>
            <symbol states="3">!</symbol>
            <symbol states="4">€</symbol>
            <symbol states="5">:-)</symbol>
        </key>

        <key id="v">
            <symbol states="1">v</symbol>
            <symbol states="2">V</symbol>
            <symbol states="3">"</symbol>
            <symbol states="4">£</symbol>
            <symbol states="5">:-(</symbol>
        </key>
        
        <key id="b">
            <symbol states="1">b</symbol>
            <symbol states="2">B</symbol>
            <symbol states="3">'</symbol>
            <symbol states="4">¥</symbol>
            <symbol states="5">;-)</symbol>
        </key>
        
        <key id="n">
            <symbol states="1">n</symbol>
            <symbol states="2">N</symbol>
            <symbol states="3">:</symbol>
            <symbol states="4">¢</symbol>
            <symbol states="5">:-P</symbol>
        </key>
        
        <key id="m">
            <symbol states="1">m</symbol>
            <symbol states="2">M</symbol>
            <symbol states="3">;</symbol>
            <symbol states="4">₩</symbol>
            <symbol states="5">=-o</symbol>
        </key>

        <key id="BackSpace" repeatable="yes" constraint="extend" icon="@DATADIR:backspace.png"/>
    </row>
                 
</keyboard>
