=== Power535/ilixi/data/compositor.dtd
<!ELEMENT settings (mem_monitor, animations, notifications) >
    <!ELEMENT mem_monitor (mem_states, page_faults) >
    <!ATTLIST mem_monitor enabled (yes|no) "yes" >
        <!ELEMENT mem_states (low, critical)>
        <!ELEMENT page_faults (low, critical)>
            <!ELEMENT low (#PCDATA) >
            <!ELEMENT critical (#PCDATA) >
    <!ELEMENT animations (slide, show, hide) >
    <!ATTLIST animations enabled (yes|no) "yes" >
        <!ELEMENT slide (duration) >
        <!ELEMENT show (zoom, opacity, duration) >
        <!ELEMENT hide (zoom, opacity, duration) >
            <!ELEMENT zoom (#PCDATA) >
            <!ELEMENT opacity (#PCDATA) >
            <!ELEMENT duration (#PCDATA) >
    <!ELEMENT notifications (duration) >

=== Power535/ilixi/data/compositor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings PUBLIC "-//ilixi//DTD Compositor v1//EN" "http://www.ilixi.org/dtd/compositor.dtd">
<settings>
	<mem_monitor>
		<mem_states>
			<low>0.5</low>
			<critical>0.3</critical>
		</mem_states>
		<page_faults>
			<low>10</low>
			<critical>50</critical>
		</page_faults>
	</mem_monitor>

	<animations enabled="no">
		<slide>
			<duration>300</duration>
		</slide>
		<show>
			<zoom>0</zoom>
			<opacity>1</opacity>
			<duration>300</duration>
		</show>
		<hide>
			<zoom>0</zoom>
			<opacity>1</opacity>
			<duration>300</duration>
		</hide>
	</animations>

	<notifications>
		<duration>3000</duration>
	</notifications>
</settings>
