=== Power535/ilixi/data/font_pack.dtd
<!ELEMENT FontPack (ButtonFont, DefaultFont, InputFont, TitleFont, InfoFont, CustomFont*) >
	<!ELEMENT ButtonFont  (Name, Size, FontStyle*) >
	<!ELEMENT DefaultFont (Name, Size, FontStyle*) >
	<!ELEMENT InputFont   (Name, Size, FontStyle*) >
	<!ELEMENT TitleFont   (Name, Size, FontStyle*) >
	<!ELEMENT InfoFont   (Name, Size, FontStyle*) >
	<!ELEMENT CustomFont   (Name, Size, FontStyle*) >
	<!ATTLIST CustomFont name CDATA #REQUIRED >
		<!ELEMENT Name      (#PCDATA) >
		<!ELEMENT Size      (#PCDATA) >
		<!ELEMENT FontStyle (#PCDATA) >

=== Power535/ilixi/data/themes/default/fonts_ja_JP.xml
<?xml version="1.0"?>
<!DOCTYPE FontPack PUBLIC "-//ilixi//DTD Fonts v1//EN" "http://www.ilixi.org/dtd/font_pack.dtd">
<FontPack>
	<ButtonFont>
		<Name>Sazanami Gothic</Name>
		<Size>16</Size>
		<FontStyle>bold</FontStyle>
	</ButtonFont>

	<DefaultFont>
		<Name>Sazanami Gothic</Name>
		<Size>14</Size>
	</DefaultFont>

	<InputFont>
		<Name>Sazanami Gothic</Name>
		<Size>16</Size>
	</InputFont>

	<TitleFont>
		<Name>Sazanami Gothic</Name>
		<Size>16</Size>
		<FontStyle>bold</FontStyle>
	</TitleFont>
</FontPack>
