=== Power535/ilixi/data/palette.dtd
<!ELEMENT palette (application, default, disabled, exposed, pressed)>

<!ELEMENT color (hex | (red, green, blue)) >
<!-- alpha transparency [0-1] -->
<!ATTLIST color alpha CDATA "255">
	<!-- 6 digit hex color -->
	<!ELEMENT hex (#PCDATA)>
	<!-- RGB components [0-255] -->
	<!ELEMENT red (#PCDATA)>
	<!ELEMENT green (#PCDATA)>
	<!ELEMENT blue (#PCDATA)>

<!-- Interactive area colors -->
<!ELEMENT base (color)>
<!ELEMENT baseText (color)>
<!ELEMENT baseAlt (color)>
<!ELEMENT baseAltText (color)>

<!-- Background fill colors -->
<!ELEMENT bgBottom (color)> 
<!ELEMENT bgMid (color)>
<!ELEMENT bgTop (color)>

<!-- Border colors -->
<!ELEMENT borderBottom (color)>
<!ELEMENT borderMid (color)>
<!ELEMENT borderTop (color)>

<!-- Focus indication colors -->
<!ELEMENT focusBottom (color)>
<!ELEMENT focusMid (color)>
<!ELEMENT focusTop (color)>

<!-- Fill inside colors -->
<!ELEMENT fillBottom (color)>
<!ELEMENT fillMid (color)>
<!ELEMENT fillTop (color)>

<!-- Text drawing colors -->		
<!ELEMENT text (color)>
<!ELEMENT textDisabled (color)>

<!-- Color groups -->	
<!ELEMENT application (bgBottom, bgMid, bgTop, focusBottom, focusMid, focusTop, text, textDisabled)>
<!ELEMENT default (base, baseText, baseAlt, baseAltText, bgBottom, bgMid, bgTop, borderBottom, borderMid, borderTop, fillBottom, fillMid, fillTop, text)>
<!ELEMENT disabled (base, baseText, baseAlt, baseAltText, bgBottom, bgMid, bgTop, borderBottom, borderMid, borderTop, fillBottom, fillMid, fillTop, text)>
<!ELEMENT exposed (base, baseText, baseAlt, baseAltText, bgBottom, bgMid, bgTop, borderBottom, borderMid, borderTop, fillBottom, fillMid, fillTop, text)>
<!ELEMENT pressed (base, baseText, baseAlt, baseAltText, bgBottom, bgMid, bgTop, borderBottom, borderMid, borderTop, fillBottom, fillMid, fillTop, text)>

=== Power535/ilixi/data/themes/default/palette.xml
<?xml version="1.0"?>
<!DOCTYPE palette PUBLIC "-//ilixi//DTD Palette v2//EN" "http://www.ilixi.org/dtd/palette.dtd">
<palette>
	<application>
		<bg>
			<color>
				<hex>666666</hex>
			</color>
		</bg>
		<focus>
			<color>
				<hex>577E04</hex>
			</color>
		</focus>
		<text>
			<color>
				<hex>333333</hex>
			</color>
		</text>
		<textDisabled>
			<color>
				<hex>747474</hex>
			</color>
		</textDisabled>
	</application>
	<default>
		<base>
			<color>
				<hex>FFFFFF</hex>
			</color>
		</base>
		<baseText>
			<color>
				<hex>000000</hex>
			</color>
		</baseText>
		<baseAlt>
			<color>
				<hex>E0E0E0</hex>
			</color>
		</baseAlt>
		<baseAltText>
			<color>
				<hex>000000</hex>
			</color>
		</baseAltText>
		<bg>
			<color>
				<hex>474747</hex>
			</color>
		</bg>
		<border>
			<color>
				<hex>141414</hex>
			</color>
		</border>
		<fill>
			<color>
				<hex>375C86</hex>
			</color>
		</fill>
		<text>
			<color>
				<hex>333333</hex>
			</color>
		</text>
	</default>
	<disabled>
		<base>
			<color>
				<hex>515151</hex>
			</color>
		</base>
		<baseText>
			<color>
				<hex>1A1A1A</hex>
			</color>
		</baseText>
		<baseAlt>
			<color>
				<hex>323232</hex>
			</color>
		</baseAlt>
		<baseAltText>
			<color>
				<hex>515151</hex>
			</color>
		</baseAltText>
		<bg>
			<color>
				<hex>4B4B4B</hex>
			</color>
		</bg>
		<border>
			<color>
				<hex>303030</hex>
			</color>
		</border>
		<fill>
			<color>
				<hex>45505D</hex>
			</color>
		</fill>
		<text>
			<color>
				<hex>747474</hex>
			</color>
		</text>
	</disabled>
	<exposed>
		<base>
			<color>
				<hex>FFFFFF</hex>
			</color>
		</base>
		<baseText>
			<color>
				<hex>000000</hex>
			</color>
		</baseText>
		<baseAlt>
			<color>
				<hex>E0E0E0</hex>
			</color>
		</baseAlt>
		<baseAltText>
			<color>
				<hex>000000</hex>
			</color>
		</baseAltText>
		<bg>
			<color>
				<hex>545454</hex>
			</color>
		</bg>
		<border>
			<color>
				<hex>000000</hex>
			</color>
		</border>
		<fill>
			<color>
				<hex>375C86</hex>
			</color>
		</fill>
		<text>
			<color>
				<hex>333333</hex>
			</color>
		</text>
	</exposed>
	<pressed>
		<base>
			<color>
				<hex>FFFFFF</hex>
			</color>
		</base>
		<baseText>
			<color>
				<hex>000000</hex>
			</color>
		</baseText>
		<baseAlt>
			<color>
				<hex>E0E0E0</hex>
			</color>
		</baseAlt>
		<baseAltText>
			<color>
				<hex>000000</hex>
			</color>
		</baseAltText>
		<bg>
			<color>
				<hex>626262</hex>
			</color>
		</bg>
		<border>
			<color>
				<hex>000000</hex>
			</color>
		</border>
		<fill>
			<color>
				<hex>375C86</hex>
			</color>
		</fill>
		<text>
			<color>
				<hex>000000</hex>
			</color>
		</text>
	</pressed>
</palette>

=== Power535/ilixi/data/themes/dark/palette.xml
<?xml version="1.0"?>
<!DOCTYPE palette PUBLIC "-//ilixi//DTD Palette v2//EN" "http://www.ilixi.org/dtd/palette.dtd">
<palette>
	<application>
		<bg>
			<color>
				<hex>333333</hex>
			</color>
		</bg>
		<focus>
			<color>
				<hex>3399FF</hex>
			</color>
		</focus>
		<text>
			<color>
				<hex>FFFFFF</hex>
			</color>
		</text>
		<textDisabled>
			<color>
				<hex>999999</hex>
			</color>
		</textDisabled>
	</application>
	<default>
		<base>
			<color>
				<hex>626262</hex>
			</color>
		</base>
		<baseText>
			<color>
				<hex>FFFFFF</hex>
			</color>
		</baseText>
		<baseAlt>
			<color>
				<hex>919191</hex>
			</color>
		</baseAlt>
		<baseAltText>
			<color>
				<hex>FFFFFF</hex>
			</color>
		</baseAltText>
		<bg>
			<color>
				<hex>474747</hex>
			</color>
		</bg>
		<border>
			<color>
				<hex>141414</hex>
			</color>
		</border>
		<fill>
			<color>
				<hex>375C86</hex>
			</color>
		</fill>
		<text>
			<color>
				<hex>E6E6E6</hex>
			</color>
		</text>
	</default>
	<disabled>
		<base>
			<color>
				<hex>4C4C4C</hex>
			</color>
		</base>
		<baseText>
			<color>
				<hex>808080</hex>
			</color>
		</baseText>
		<baseAlt>
			<color>
				<hex>333333</hex>
			</color>
		</baseAlt>
		<baseAltText>
			<color>
				<hex>666666</hex>
			</color>
		</baseAltText>
		<bg>
			<color>
				<hex>4B4B4B</hex>
			</color>
		</bg>
		<border>
			<color>
				<hex>303030</hex>
			</color>
		</border>
		<fill>
			<color>
				<hex>45505D</hex>
			</color>
		</fill>
		<text>
			<color>
				<hex>4C4C4C</hex>
			</color>
		</text>
	</disabled>
	<exposed>
		<base>
			<color>
				<hex>4C4C4C</hex>
			</color>
		</base>
		<baseText>
			<color>
				<hex>808080</hex>
			</color>
		</baseText>
		<baseAlt>
			<color>
				<hex>333333</hex>
			</color>
		</baseAlt>
		<baseAltText>
			<color>
				<hex>666666</hex>
			</color>
		</baseAltText>
		<bg>
			<color>
				<hex>4B4B4B</hex>
			</color>
		</bg>
		<border>
			<color>
				<hex>303030</hex>
			</color>
		</border>
		<fill>
			<color>
				<hex>45505D</hex>
			</color>
		</fill>
		<text>
			<color>
				<hex>CCCCCC</hex>
			</color>
		</text>
	</exposed>
	<pressed>
		<base>
			<color>
				<hex>4C4C4C</hex>
			</color>
		</base>
		<baseText>
			<color>
				<hex>808080</hex>
			</color>
		</baseText>
		<baseAlt>
			<color>
				<hex>333333</hex>
			</color>
		</baseAlt>
		<baseAltText>
			<color>
				<hex>666666</hex>
			</color>
		</baseAltText>
		<bg>
			<color>
				<hex>4B4B4B</hex>
			</color>
		</bg>
		<border>
			<color>
				<hex>303030</hex>
			</color>
		</border>
		<fill>
			<color>
				<hex>45505D</hex>
			</color>
		</fill>
		<text>
			<color>
				<hex>E6E6E6</hex>
			</color>
		</text>
	</pressed>
</palette>

=== Power535/ilixi/data/def_palette.xml
<?xml version="1.0"?>
<!--
<!DOCTYPE palette SYSTEM "http://www.ilixi.org/palette.dtd">
-->
<!DOCTYPE palette SYSTEM "palette.dtd">
<palette>
      <application>
            <bgBottom>
                  <color alpha="155">
                        <hex>000000</hex>
                  </color>
            </bgBottom>
            <bgMid>
                  <color>
                        <hex>000000</hex>
                  </color>
            </bgMid>
            <bgTop>
                  <color alpha="128">
                        <hex>141414</hex>
                  </color>
            </bgTop>
            <focusBottom>
                  <color>
                        <hex>FF6633</hex>
                  </color>
            </focusBottom>
            <focusMid>
                  <color>
                        <hex>FFFFFF</hex>
                  </color>
            </focusMid>
            <focusTop>
                  <color>
                        <hex>5196FF</hex>
                  </color>
            </focusTop>
            <text>
                  <color>
                        <hex>FFFFFF</hex>
                  </color>
            </text>
            <textDisabled>
                  <color>
                        <hex>747474</hex>
                  </color>
            </textDisabled>
      </application>
      <default>
            <base>
                  <color>
                        <hex>FFFFFF</hex>
                  </color>
            </base>
            <baseText>
                  <color>
                        <hex>000000</hex>
                  </color>
            </baseText>
            <baseAlt>
                  <color>
                        <hex>E0E0E0</hex>
                  </color>
            </baseAlt>
            <baseAltText>
                  <color>
                        <hex>000000</hex>
                  </color>
            </baseAltText>
            <bgBottom>
                  <color>
                        <hex>474747</hex>
                  </color>
            </bgBottom>
            <bgMid>
                  <color>
                        <hex>FFFFFF</hex>
                  </color>
            </bgMid>
            <bgTop>
                  <color>
                        <hex>686868</hex>
                  </color>
            </bgTop>
            <borderBottom>
                  <color>
                        <hex>141414</hex>
                  </color>
            </borderBottom>
            <borderMid>
                  <color>
                        <hex>717171</hex>
                  </color>
            </borderMid>
            <borderTop>
                  <color>
                        <hex>686868</hex>
                  </color>
            </borderTop>
            <fillBottom>
                  <color>
                        <hex>375C86</hex>
                  </color>
            </fillBottom>
            <fillMid>
                  <color>
                        <hex>5286B9</hex>
                  </color>
            </fillMid>
            <fillTop>
                  <color>
                        <hex>65A2E1</hex>
                  </color>
            </fillTop>
            <text>
                  <color>
                        <hex>FFFFFF</hex>
                  </color>
            </text>
      </default>
      <disabled>
            <base>
                  <color>
                        <hex>515151</hex>
                  </color>
            </base>
            <baseText>
                  <color>
                        <hex>1A1A1A</hex>
                  </color>
            </baseText>
            <baseAlt>
                  <color>
                        <hex>323232</hex>
                  </color>
            </baseAlt>
            <baseAltText>
                  <color>
                        <hex>515151</hex>
                  </color>
            </baseAltText>
            <bgBottom>
                  <color>
                        <hex>4B4B4B</hex>
                  </color>
            </bgBottom>
            <bgMid>
                  <color>
                        <hex>747474</hex>
                  </color>
            </bgMid>
            <bgTop>
                  <color>
                        <hex>424242</hex>
                  </color>
            </bgTop>
            <borderBottom>
                  <color>
                        <hex>303030</hex>
                  </color>
            </borderBottom>
            <borderMid>
                  <color>
                        <hex>565656</hex>
                  </color>
            </borderMid>
            <borderTop>
                  <color>
                        <hex>303030</hex>
                  </color>
            </borderTop>
            <fillBottom>
                  <color>
                        <hex>45505D</hex>
                  </color>
            </fillBottom>
            <fillMid>
                  <color>
                        <hex>3A5A69</hex>
                  </color>
            </fillMid>
            <fillTop>
                  <color>
                        <hex>4D5F72</hex>
                  </color>
            </fillTop>
            <text>
                  <color>
                        <hex>747474</hex>
                  </color>
            </text>
      </disabled>
      <exposed>
            <base>
                  <color>
                        <hex>FFFFFF</hex>
                  </color>
            </base>
            <baseText>
                  <color>
                        <hex>000000</hex>
                  </color>
            </baseText>
            <baseAlt>
                  <color>
                        <hex>E0E0E0</hex>
                  </color>
            </baseAlt>
            <baseAltText>
                  <color>
                        <hex>000000</hex>
                  </color>
            </baseAltText>
            <bgBottom>
                  <color>
                        <hex>545454</hex>
                  </color>
            </bgBottom>
            <bgMid>
                  <color>
                        <hex>FFFFFF</hex>
                  </color>
            </bgMid>
            <bgTop>
                  <color>
                        <hex>767676</hex>
                  </color>
            </bgTop>
            <borderBottom>
                  <color>
                        <hex>000000</hex>
                  </color>
            </borderBottom>
            <borderMid>
                  <color>
                        <hex>969696</hex>
                  </color>
            </borderMid>
            <borderTop>
                  <color>
                        <hex>515151</hex>
                  </color>
            </borderTop>
            <fillBottom>
                  <color>
                        <hex>375C86</hex>
                  </color>
            </fillBottom>
            <fillMid>
                  <color>
                        <hex>5286B9</hex>
                  </color>
            </fillMid>
            <fillTop>
                  <color>
                        <hex>65A2E1</hex>
                  </color>
            </fillTop>
            <text>
                  <color>
                        <hex>FFFFFF</hex>
                  </color>
            </text>
      </exposed>
      <pressed>
            <base>
                  <color>
                        <hex>FFFFFF</hex>
                  </color>
            </base>
            <baseText>
                  <color>
                        <hex>000000</hex>
                  </color>
            </baseText>
            <baseAlt>
                  <color>
                        <hex>E0E0E0</hex>
                  </color>
            </baseAlt>
            <baseAltText>
                  <color>
                        <hex>000000</hex>
                  </color>
            </baseAltText>
            <bgBottom>
                  <color>
                        <hex>626262</hex>
                  </color>
            </bgBottom>
            <bgMid>
                  <color>
                        <hex>FFFFFF</hex>
                  </color>
            </bgMid>
            <bgTop>
                  <color>
                        <hex>414141</hex>
                  </color>
            </bgTop>
            <borderBottom>
                  <color>
                        <hex>000000</hex>
                  </color>
            </borderBottom>
            <borderMid>
                  <color>
                        <hex>808080</hex>
                  </color>
            </borderMid>
            <borderTop>
                  <color>
                        <hex>323232</hex>
                  </color>
            </borderTop>
            <fillBottom>
                  <color>
                        <hex>375C86</hex>
                  </color>
            </fillBottom>
            <fillMid>
                  <color>
                        <hex>5286B9</hex>
                  </color>
            </fillMid>
            <fillTop>
                  <color>
                        <hex>65A2E1</hex>
                  </color>
            </fillTop>
            <text>
                  <color>
                        <hex>F0F0F0</hex>
                  </color>
            </text>
      </pressed>
</palette>
