=== Power535/ilixi/data/style.dtd
<!ELEMENT style (fonts, icons, pack)>

<!ELEMENT fonts (buttonFont, defaultFont, inputFont, titleFont) >
	<!ELEMENT buttonFont (file, size, fontStyle*)>
	<!ELEMENT defaultFont (file, size, fontStyle*)>
	<!ELEMENT inputFont (file, size, fontStyle*)>
	<!ELEMENT titleFont (file, size, fontStyle*)>
		<!ELEMENT file (#PCDATA)>
		<!ELEMENT size (#PCDATA)>
		<!ELEMENT fontStyle (#PCDATA)>

<!ELEMENT icons (plus, minus, check, tri-check, radioOff, radioOn)>
<!ATTLIST icons resource CDATA #REQUIRED>
	<!ELEMENT plus EMPTY>
	<!ATTLIST plus x CDATA #REQUIRED>
	<!ATTLIST plus y CDATA #REQUIRED>
	<!ATTLIST plus w CDATA #REQUIRED>
	<!ATTLIST plus h CDATA #REQUIRED>

	<!ELEMENT minus EMPTY>
	<!ATTLIST minus x CDATA #REQUIRED>
	<!ATTLIST minus y CDATA #REQUIRED>
	<!ATTLIST minus w CDATA #REQUIRED>
	<!ATTLIST minus h CDATA #REQUIRED>

	<!ELEMENT check EMPTY>
	<!ATTLIST check x CDATA #REQUIRED>
	<!ATTLIST check y CDATA #REQUIRED>
	<!ATTLIST check w CDATA #REQUIRED>
	<!ATTLIST check h CDATA #REQUIRED>

	<!ELEMENT tri-check EMPTY>
	<!ATTLIST tri-check x CDATA #REQUIRED>
	<!ATTLIST tri-check y CDATA #REQUIRED>
	<!ATTLIST tri-check w CDATA #REQUIRED>
	<!ATTLIST tri-check h CDATA #REQUIRED>

	<!ELEMENT radioOff EMPTY>
	<!ATTLIST radioOff x CDATA #REQUIRED>
	<!ATTLIST radioOff y CDATA #REQUIRED>
	<!ATTLIST radioOff w CDATA #REQUIRED>
	<!ATTLIST radioOff h CDATA #REQUIRED>

	<!ELEMENT radioOn EMPTY>
	<!ATTLIST radioOn x CDATA #REQUIRED>
	<!ATTLIST radioOn y CDATA #REQUIRED>
	<!ATTLIST radioOn w CDATA #REQUIRED>
	<!ATTLIST radioOn h CDATA #REQUIRED>

<!ELEMENT pack (PushButton, CheckBox, RadioButton, ProgressBar, Slider, Frame, LineInput, Tab, ToolButton)>
<!ATTLIST pack resource CDATA #REQUIRED>

	<!ELEMENT PushButton (default, disabled, pressed, exposed, focused)>
	<!ELEMENT CheckBox (default, disabled, pressed, exposed, focused)>
	<!ELEMENT RadioButton (default, disabled, pressed, exposed, focused)>
	<!ELEMENT ProgressBar (default, disabled, indicator)>
	<!ELEMENT Slider (default, disabled, indicator)>
	<!ELEMENT Frame (default, disabled)>
	<!ELEMENT Tab (default, disabled)>
	<!ELEMENT LineInput (default, disabled, pressed, exposed, focused)>
	<!ELEMENT ToolButton (default, disabled, pressed, exposed, focused)>
	<!ELEMENT indicator (default, disabled, pressed?, exposed?, focused?)>

	<!ELEMENT default 	((left) | (left, mid, right) | (top-left, top-mid, top-right, left, mid, right, bottom-left, bottom-mid, bottom-right))>
	<!ELEMENT pressed 	((left) | (left, mid, right) | (top-left, top-mid, top-right, left, mid, right, bottom-left, bottom-mid, bottom-right))>
	<!ELEMENT exposed 	((left) | (left, mid, right) | (top-left, top-mid, top-right, left, mid, right, bottom-left, bottom-mid, bottom-right))>
	<!ELEMENT disabled 	((left) | (left, mid, right) | (top-left, top-mid, top-right, left, mid, right, bottom-left, bottom-mid, bottom-right))>
	<!ELEMENT focused 	((left) | (left, mid, right) | (top-left, top-mid, top-right, left, mid, right, bottom-left, bottom-mid, bottom-right))>

	<!ELEMENT left EMPTY>
	<!ATTLIST left x CDATA #REQUIRED>
	<!ATTLIST left y CDATA #REQUIRED>
	<!ATTLIST left w CDATA #REQUIRED>
	<!ATTLIST left h CDATA #REQUIRED>

	<!ELEMENT mid EMPTY>
	<!ATTLIST mid x CDATA #REQUIRED>
	<!ATTLIST mid y CDATA #REQUIRED>
	<!ATTLIST mid w CDATA #REQUIRED>
	<!ATTLIST mid h CDATA #REQUIRED>

	<!ELEMENT right EMPTY>
	<!ATTLIST right x CDATA #REQUIRED>
	<!ATTLIST right y CDATA #REQUIRED>
	<!ATTLIST right w CDATA #REQUIRED>
	<!ATTLIST right h CDATA #REQUIRED>


	<!ELEMENT top-left EMPTY>
	<!ATTLIST top-left x CDATA #REQUIRED>
	<!ATTLIST top-left y CDATA #REQUIRED>
	<!ATTLIST top-left w CDATA #REQUIRED>
	<!ATTLIST top-left h CDATA #REQUIRED>

	<!ELEMENT top-mid EMPTY>
	<!ATTLIST top-mid x CDATA #REQUIRED>
	<!ATTLIST top-mid y CDATA #REQUIRED>
	<!ATTLIST top-mid w CDATA #REQUIRED>
	<!ATTLIST top-mid h CDATA #REQUIRED>

	<!ELEMENT top-right EMPTY>
	<!ATTLIST top-right x CDATA #REQUIRED>
	<!ATTLIST top-right y CDATA #REQUIRED>
	<!ATTLIST top-right w CDATA #REQUIRED>
	<!ATTLIST top-right h CDATA #REQUIRED>


	<!ELEMENT bottom-left EMPTY>
	<!ATTLIST bottom-left x CDATA #REQUIRED>
	<!ATTLIST bottom-left y CDATA #REQUIRED>
	<!ATTLIST bottom-left w CDATA #REQUIRED>
	<!ATTLIST bottom-left h CDATA #REQUIRED>

	<!ELEMENT bottom-mid EMPTY>
	<!ATTLIST bottom-mid x CDATA #REQUIRED>
	<!ATTLIST bottom-mid y CDATA #REQUIRED>
	<!ATTLIST bottom-mid w CDATA #REQUIRED>
	<!ATTLIST bottom-mid h CDATA #REQUIRED>

	<!ELEMENT bottom-right EMPTY>
	<!ATTLIST bottom-right x CDATA #REQUIRED>
	<!ATTLIST bottom-right y CDATA #REQUIRED>
	<!ATTLIST bottom-right w CDATA #REQUIRED>
	<!ATTLIST bottom-right h CDATA #REQUIRED>

=== Power535/ilixi/data/def_style.xml
<?xml version="1.0"?>
<!DOCTYPE style PUBLIC "-//ilixi//DTD Style v2//EN" "http://www.ilixi.org/dtd/style.dtd">
<style>
	<fonts>
		<buttonFont>
			<file>Sans</file>
			<size>16</size>
			<fontStyle>bold</fontStyle>
		</buttonFont>

		<defaultFont>
			<file>Sans</file>
			<size>14</size>
		</defaultFont>

		<inputFont>
			<file>Sans</file>
			<size>14</size>
		</inputFont>

		<titleFont>
			<file>Sans</file>
			<size>18</size>
			<fontStyle>bold</fontStyle>
		</titleFont>
	</fonts>

	<icons resource="/images/ui-icons.png">
		<plus x="0" y="0" w="12" h="34" />
		<minus x="0" y="0" w="12" h="34" />
		<check x="107" y="104" w="18" h="18" />
		<tri-check x="128" y="107" w="18" h="18" />
		<radioOff x="105" y="130" w="16" h="16" />
		<radioOn x="125" y="130" w="16" h="16" />
	</icons>

	<pack resource="/images/ui-pack.png">
		<PushButton>
			<def3>
				<left x="5" y="7" w="16" h="45" />
				<mid x="21" y="7" w="47" h="45" />
				<right x="68" y="7" w="16" h="45" />
			</def3>

			<pre3>
				<left x="90" y="7" w="16" h="45" />
				<mid x="106" y="7" w="47" h="45" />
				<right x="153" y="7" w="16" h="45" />
			</pre3>

			<exp3>
				<left x="175" y="7" w="16" h="45" />
				<mid x="191" y="7" w="47" h="45" />
				<right x="238" y="7" w="16" h="45" />
			</exp3>

			<dis3>
				<left x="260" y="7" w="16" h="45" />
				<mid x="276" y="7" w="47" h="45" />
				<right x="323" y="7" w="16" h="45" />
			</dis3>

			<foc3>
				<left x="345" y="7" w="16" h="45" />
				<mid x="361" y="7" w="47" h="45" />
				<right x="408" y="7" w="16" h="45" />
			</foc3>
		</PushButton>

		<ToolButton>
			<def9>
				<top-left x="5" y="57" w="5" h="5" />
				<top-mid x="10" y="57" w="70" h="5" />
				<top-right x="80" y="57" w="7" h="5" />
				<left x="5" y="62" w="5" h="31" />
				<mid x="10" y="62" w="70" h="31" />
				<right x="80" y="62" w="7" h="31" />
				<bottom-left x="5" y="93" w="5" h="7" />
				<bottom-mid x="10" y="93" w="70" h="7" />
				<bottom-right x="80" y="93" w="7" h="7" />
			</def9>

			<pre9>
				<top-left x="90" y="57" w="5" h="5" />
				<top-mid x="95" y="57" w="70" h="5" />
				<top-right x="165" y="57" w="7" h="5" />
				<left x="90" y="62" w="5" h="31" />
				<mid x="95" y="62" w="70" h="31" />
				<right x="165" y="62" w="7" h="31" />
				<bottom-left x="90" y="93" w="5" h="7" />
				<bottom-mid x="95" y="93" w="70" h="7" />
				<bottom-right x="165" y="93" w="7" h="7" />
			</pre9>

			<exp9>
				<top-left x="175" y="57" w="5" h="5" />
				<top-mid x="180" y="57" w="70" h="5" />
				<top-right x="250" y="57" w="7" h="5" />
				<left x="175" y="62" w="5" h="31" />
				<mid x="180" y="62" w="70" h="31" />
				<right x="250" y="62" w="7" h="31" />
				<bottom-left x="175" y="93" w="5" h="7" />
				<bottom-mid x="180" y="93" w="70" h="7" />
				<bottom-right x="250" y="93" w="7" h="7" />
			</exp9>

			<dis9>
				<top-left x="260" y="57" w="5" h="5" />
				<top-mid x="265" y="57" w="70" h="5" />
				<top-right x="335" y="57" w="7" h="5" />
				<left x="260" y="62" w="5" h="31" />
				<mid x="265" y="62" w="70" h="31" />
				<right x="335" y="62" w="7" h="31" />
				<bottom-left x="260" y="93" w="5" h="7" />
				<bottom-mid x="265" y="93" w="70" h="7" />
				<bottom-right x="335" y="93" w="7" h="7" />
			</dis9>

			<foc9>
				<top-left x="345" y="57" w="5" h="5" />
				<top-mid x="350" y="57" w="70" h="5" />
				<top-right x="420" y="57" w="7" h="5" />
				<left x="345" y="62" w="5" h="31" />
				<mid x="350" y="62" w="70" h="31" />
				<right x="420" y="62" w="7" h="31" />
				<bottom-left x="345" y="93" w="5" h="7" />
				<bottom-mid x="350" y="93" w="70" h="7" />
				<bottom-right x="420" y="93" w="7" h="7" />
			</foc9>
		</ToolButton>

		<CheckBox>
			<def1>
				<left x="5" y="107" w="18" h="18" />
			</def1>
			<pre1>
				<left x="25" y="107" w="18" h="18" />
			</pre1>
			<exp1>
				<left x="45" y="107" w="18" h="18" />
			</exp1>
			<dis1>
				<left x="65" y="107" w="18" h="18" />
			</dis1>

			<foc1>
				<left x="85" y="107" w="18" h="18" />
			</foc1>
		</CheckBox>

		<RadioButton>
			<def1>
				<left x="5" y="130" w="18" h="18" />
			</def1>
			<pre1>
				<left x="25" y="130" w="18" h="18" />
			</pre1>
			<exp1>
				<left x="45" y="130" w="18" h="18" />
			</exp1>
			<dis1>
				<left x="65" y="130" w="18" h="18" />
			</dis1>
			<foc1>
				<left x="85" y="130" w="18" h="18" />
			</foc1>
		</RadioButton>

		<ProgressBar>
			<def3>
				<left x="5" y="150" w="5" h="8" />
				<mid x="10" y="150" w="160" h="8" />
				<right x="170" y="150" w="5" h="8" />
			</def3>
			<dis3>
				<left x="5" y="170" w="5" h="8" />
				<mid x="10" y="170" w="160" h="8" />
				<right x="170" y="170" w="5" h="8" />
			</dis3>

			<pIndicator>
				<def3>
					<left x="5" y="160" w="5" h="8" />
					<mid x="10" y="160" w="160" h="8" />
					<right x="170" y="160" w="5" h="8" />
				</def3>

				<dis3>
					<left x="5" y="180" w="5" h="8" />
					<mid x="10" y="180" w="160" h="8" />
					<right x="170" y="180" w="5" h="8" />
				</dis3>
			</pIndicator>
		</ProgressBar>

		<Slider>
			<def3>
				<left x="5" y="191" w="10" h="16" />
				<mid x="15" y="191" w="150" h="16" />
				<right x="165" y="191" w="10" h="16" />
			</def3>
			<dis3>
				<left x="5" y="211" w="10" h="16" />
				<mid x="15" y="211" w="150" h="16" />
				<right x="165" y="211" w="10" h="16" />
			</dis3>	
					
			<pre3>
				<left x="405" y="102" w="16" h="10" />
				<mid x="405" y="112" w="16" h="150" />
				<right x="405" y="262" w="16" h="10" />
			</pre3>
			<exp3>
				<left x="385" y="102" w="16" h="10" />
				<mid x="385" y="112" w="16" h="150" />
				<right x="385" y="262" w="16" h="10" />
			</exp3>
			
			<sIndicator>
				<def1>
					<left x="6" y="232" w="14" h="14" />
				</def1>
				<pre1>
					<left x="26" y="232" w="14" h="14" />
				</pre1>
				<exp1>
					<left x="46" y="232" w="14" h="14" />
				</exp1>
				<dis1>
					<left x="66" y="232" w="14" h="14" />
				</dis1>
				<foc1>
					<left x="86" y="232" w="14" h="14" />
				</foc1>
			</sIndicator>
		</Slider>

		<Frame>
			<def9>
				<top-left x="284" y="183" w="16" h="16" />
				<top-mid x="300" y="183" w="53" h="16" />
				<top-right x="353" y="183" w="16" h="16" />
				<left x="284" y="199" w="16" h="52" />
				<mid x="300" y="199" w="53" h="52" />
				<right x="353" y="199" w="16" h="52" />
				<bottom-left x="284" y="251" w="16" h="16" />
				<bottom-mid x="300" y="251" w="53" h="16" />
				<bottom-right x="353" y="251" w="16" h="16" />
			</def9>
			<dis9>
				<top-left x="194" y="183" w="16" h="16" />
				<top-mid x="210" y="183" w="53" h="16" />
				<top-right x="263" y="183" w="16" h="16" />
				<left x="194" y="199" w="16" h="52" />
				<mid x="210" y="199" w="53" h="52" />
				<right x="263" y="199" w="16" h="52" />
				<bottom-left x="194" y="251" w="16" h="16" />
				<bottom-mid x="210" y="251" w="53" h="16" />
				<bottom-right x="263" y="251" w="16" h="16" />
			</dis9>
		</Frame>

		<Tab>
			<def9>
				<top-left x="194" y="108" w="16" h="16" />
				<top-mid x="210" y="108" w="37" h="16" />
				<top-right x="247" y="108" w="16" h="16" />
				<left x="194" y="124" w="16" h="36" />
				<mid x="210" y="124" w="37" h="36" />
				<right x="247" y="124" w="16" h="36" />
				<bottom-left x="194" y="160" w="16" h="16" />
				<bottom-mid x="210" y="160" w="37" h="16" />
				<bottom-right x="247" y="160" w="16" h="16" />
			</def9>
			<dis9>
				<top-left x="274" y="108" w="16" h="16" />
				<top-mid x="290" y="108" w="37" h="16" />
				<top-right x="327" y="108" w="16" h="16" />
				<left x="274" y="124" w="16" h="36" />
				<mid x="290" y="124" w="37" h="36" />
				<right x="327" y="124" w="16" h="36" />
				<bottom-left x="274" y="160" w="16" h="16" />
				<bottom-mid x="290" y="160" w="37" h="16" />
				<bottom-right x="327" y="160" w="16" h="16" />
			</dis9>
		</Tab>

		<LineInput>
			<def9>
				<top-left x="5" y="275" w="8" h="8" />
				<top-mid x="13" y="275" w="64" h="8" />
				<top-right x="77" y="275" w="8" h="8" />
				<left x="5" y="283" w="8" h="19" />
				<mid x="13" y="283" w="64" h="19" />
				<right x="77" y="283" w="8" h="19" />
				<bottom-left x="5" y="302" w="8" h="8" />
				<bottom-mid x="13" y="302" w="64" h="8" />
				<bottom-right x="77" y="302" w="8" h="8" />
			</def9>

			<pre9>
				<top-left x="89" y="275" w="8" h="8" />
				<top-mid x="97" y="275" w="64" h="8" />
				<top-right x="161" y="275" w="8" h="8" />
				<left x="89" y="283" w="8" h="19" />
				<mid x="97" y="283" w="64" h="19" />
				<right x="161" y="283" w="8" h="19" />
				<bottom-left x="89" y="302" w="8" h="8" />
				<bottom-mid x="97" y="302" w="64" h="8" />
				<bottom-right x="161" y="302" w="8" h="8" />
			</pre9>

			<exp9>
				<top-left x="174" y="275" w="8" h="8" />
				<top-mid x="182" y="275" w="64" h="8" />
				<top-right x="246" y="275" w="8" h="8" />
				<left x="174" y="283" w="8" h="19" />
				<mid x="182" y="283" w="64" h="19" />
				<right x="246" y="283" w="8" h="19" />
				<bottom-left x="174" y="302" w="8" h="8" />
				<bottom-mid x="182" y="302" w="64" h="8" />
				<bottom-right x="246" y="302" w="8" h="8" />
			</exp9>

			<dis9>
				<top-left x="260" y="275" w="8" h="8" />
				<top-mid x="268" y="275" w="64" h="8" />
				<top-right x="332" y="275" w="8" h="8" />
				<left x="260" y="283" w="8" h="19" />
				<mid x="268" y="283" w="64" h="19" />
				<right x="332" y="283" w="8" h="19" />
				<bottom-left x="260" y="302" w="8" h="8" />
				<bottom-mid x="268" y="302" w="64" h="8" />
				<bottom-right x="332" y="302" w="8" h="8" />
			</dis9>

			<foc9>
				<top-left x="345" y="275" w="8" h="8" />
				<top-mid x="353" y="275" w="64" h="8" />
				<top-right x="417" y="275" w="8" h="8" />
				<left x="345" y="283" w="8" h="19" />
				<mid x="353" y="283" w="64" h="19" />
				<right x="417" y="283" w="8" h="19" />
				<bottom-left x="345" y="302" w="8" h="8" />
				<bottom-mid x="353" y="302" w="64" h="8" />
				<bottom-right x="417" y="302" w="8" h="8" />
			</foc9>
		</LineInput>
